// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: gnmi_dialout.proto

package proto

import (
	context "context"
	gnmi "github.com/Juniper/jtimon/gnmi/gnmi"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SubscriberClient is the client API for Subscriber service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubscriberClient interface {
	DialOutSubscriber(ctx context.Context, opts ...grpc.CallOption) (Subscriber_DialOutSubscriberClient, error)
}

type subscriberClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriberClient(cc grpc.ClientConnInterface) SubscriberClient {
	return &subscriberClient{cc}
}

func (c *subscriberClient) DialOutSubscriber(ctx context.Context, opts ...grpc.CallOption) (Subscriber_DialOutSubscriberClient, error) {
	stream, err := c.cc.NewStream(ctx, &Subscriber_ServiceDesc.Streams[0], "/Subscriber/DialOutSubscriber", opts...)
	if err != nil {
		return nil, err
	}
	x := &subscriberDialOutSubscriberClient{stream}
	return x, nil
}

type Subscriber_DialOutSubscriberClient interface {
	Send(*gnmi.SubscribeResponse) error
	Recv() (*gnmi.SubscribeRequest, error)
	grpc.ClientStream
}

type subscriberDialOutSubscriberClient struct {
	grpc.ClientStream
}

func (x *subscriberDialOutSubscriberClient) Send(m *gnmi.SubscribeResponse) error {
	return x.ClientStream.SendMsg(m)
}

func (x *subscriberDialOutSubscriberClient) Recv() (*gnmi.SubscribeRequest, error) {
	m := new(gnmi.SubscribeRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SubscriberServer is the server API for Subscriber service.
// All implementations must embed UnimplementedSubscriberServer
// for forward compatibility
type SubscriberServer interface {
	DialOutSubscriber(Subscriber_DialOutSubscriberServer) error
	mustEmbedUnimplementedSubscriberServer()
}

// UnimplementedSubscriberServer must be embedded to have forward compatible implementations.
type UnimplementedSubscriberServer struct {
}

func (UnimplementedSubscriberServer) DialOutSubscriber(Subscriber_DialOutSubscriberServer) error {
	return status.Errorf(codes.Unimplemented, "method DialOutSubscriber not implemented")
}
func (UnimplementedSubscriberServer) mustEmbedUnimplementedSubscriberServer() {}

// UnsafeSubscriberServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriberServer will
// result in compilation errors.
type UnsafeSubscriberServer interface {
	mustEmbedUnimplementedSubscriberServer()
}

func RegisterSubscriberServer(s grpc.ServiceRegistrar, srv SubscriberServer) {
	s.RegisterService(&Subscriber_ServiceDesc, srv)
}

func _Subscriber_DialOutSubscriber_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SubscriberServer).DialOutSubscriber(&subscriberDialOutSubscriberServer{stream})
}

type Subscriber_DialOutSubscriberServer interface {
	Send(*gnmi.SubscribeRequest) error
	Recv() (*gnmi.SubscribeResponse, error)
	grpc.ServerStream
}

type subscriberDialOutSubscriberServer struct {
	grpc.ServerStream
}

func (x *subscriberDialOutSubscriberServer) Send(m *gnmi.SubscribeRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *subscriberDialOutSubscriberServer) Recv() (*gnmi.SubscribeResponse, error) {
	m := new(gnmi.SubscribeResponse)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Subscriber_ServiceDesc is the grpc.ServiceDesc for Subscriber service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Subscriber_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Subscriber",
	HandlerType: (*SubscriberServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DialOutSubscriber",
			Handler:       _Subscriber_DialOutSubscriber_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "gnmi_dialout.proto",
}
